# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "LunchOption" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"choice" VARCHAR NOT NULL,"providerId" BIGINT NOT NULL);
create table "Order" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"lunchOptionId" BIGINT NOT NULL,"userId" BIGINT NOT NULL,"date" DATE NOT NULL);
create table "Providers" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL);
create table "User" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"initials" VARCHAR NOT NULL);
alter table "LunchOption" add constraint "providerForeignKey" foreign key("providerId") references "Providers"("id") on update NO ACTION on delete NO ACTION;
alter table "Order" add constraint "lunchOptionForeignKey" foreign key("lunchOptionId") references "LunchOption"("id") on update NO ACTION on delete NO ACTION;
alter table "Order" add constraint "userForeignKey" foreign key("userId") references "User"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "Order" drop constraint "lunchOptionForeignKey";
alter table "Order" drop constraint "userForeignKey";
alter table "LunchOption" drop constraint "providerForeignKey";
drop table "User";
drop table "Providers";
drop table "Order";
drop table "LunchOption";

