# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "LunchOption" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"choice" VARCHAR NOT NULL,"providerId" BIGINT NOT NULL);
create table "Providers" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL);
alter table "LunchOption" add constraint "providerForeignKey" foreign key("providerId") references "Providers"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "LunchOption" drop constraint "providerForeignKey";
drop table "Providers";
drop table "LunchOption";

